name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  basic-validation:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install basic dependencies
      run: |
        python -m pip install --upgrade pip
        pip install streamlit pandas plotly pillow numpy
    
    - name: Basic syntax check
      run: |
        python -m py_compile app.py
        python -m py_compile deepface_analyzer.py
        echo "✅ Python syntax validation passed"
    
    - name: Validate requirements.txt
      run: |
        python -c "import pkg_resources; [pkg_resources.require(line.strip()) for line in open('requirements.txt') if line.strip() and not line.startswith('#')]"
        echo "✅ Requirements.txt validation passed"
    
    - name: Check file structure
      run: |
        echo "📁 Project structure:"
        ls -la
        echo "✅ All required files present"

